/*  theme-data.js – erzeugt von tools/build-themes.py, nicht von Hand pflegen.
 *
 *  Die mitgelieferten Themes aus themes/ als Zeichenketten. Ein eigenes
 *  Theme braucht diese Datei nicht: es wird im Baukasten geladen und reist
 *  im Dokument mit.
 */
(function (global) {
  "use strict";

  global.RickCVThemeData = {
    "clean": "/* @rickcv-theme\n   name:     Clean\n   author:   RickCV\n   licence:  CC0-1.0\n   contract: 1\n   about:    Ruhige Grundform: Zeitleiste links am Rand, Datum rechts,\n             kein Schnickschnack. Das Ausgangslayout von RickCV.\n   about-en: A calm baseline: timeline along the edge, dates on the right,\n             nothing else. RickCV's original layout.\n*/\n\n/*  Es ist immer nur ein Theme aktiv, deshalb genuegt [data-template] als\n    Wurzel \u2013 der Name des Themes muss im Selektor nicht vorkommen. Welche\n    Haken es darunter gibt, steht in themes/CONTRACT.md und in der\n    Werkstatt im Baukasten, die sie auflistet.                          */\n\n[data-template] {\n  .event {\n    position: relative;\n    margin: 12px 0;\n    margin: auto 0;\n    display: flex;\n    align-items: flex-start;\n    width: 28em;\n  }\n  .date {\n    position: absolute;\n    width: 4em;\n    right: 2em;\n    display: flex;\n    flex-direction: row;\n    justify-content: flex-end;\n    text-align: right;\n    /* text-align-last: justify; */\n    left: inherit;\n  }\n  .dot {\n    width: 30px;\n    height: 30px;\n    min-width: 30px;\n    min-height: 30px;\n    border-radius: 50%;\n    display: flex;\n    align-items: center;\n    justify-content: center;\n    color: white;\n    font-size: 16px;\n    position: relative;\n    z-index: 1;\n    background: var(--color);\n    left: 0;\n    top: -6px;\n    /* left: calc(1* var(--offset)); */\n    visibility: hidden;\n  }\n  .event .content {\n    margin-left: 0;\n    padding-top: 0;\n    background-color: var(--background-color);\n    border-radius: 5px;\n    box-shadow: none;\n    position: relative;\n    left: -3.1cm;\n    /* left: calc(var(--offset) / 1 - 30px); */\n    z-index: 1;\n    /* width: 20cm; */\n    /* max-width: 16cm; */\n    min-width: 10cm;\n    flex: 10;\n    padding-right: 0;\n}\n  .event .content h3 {\n    font-size: inherit;\n    margin: 0;\n }\n\n  .event-company, .event-place {\n    color: #5a5a5a;\n  }\n\n  .content::before {\n    content: \"\";\n    position: absolute;\n    top: 4px;\n    left: 0;\n    width: 2px;\n    height: 1em;\n    \n    background: var(--accent-color);\n    border-radius: 10px;\n    z-index: 0;\n  }\n  .line {\n    position: absolute;\n    width: 4px;\n    background: var(--color);\n    left: calc(13px + var(--offset) / 4);\n    top: 0;\n    border-radius: 20px;\n    z-index: 0;\n    height: 0;\n    display: none;\n  }\n  .timeline::before {\n    /* display: none; */\n    visibility: hidden;\n  }\n}\n",
    "dynaline": "/* @rickcv-theme\n   name:     Dynaline\n   author:   RickCV\n   licence:  CC0-1.0\n   contract: 1\n   about:    Die Zeitleiste wird zur Achse: Stationen sitzen auf einer\n             durchgehenden Linie, die Dauer bestimmt ihren Abstand.\n   about-en: The timeline becomes the axis: stations sit on one continuous\n             line, and how long they lasted sets their distance.\n*/\n\n[data-template] {\n\n  .timeline {\n    left: -0.6cm;\n  }\n\n  .date {\n    position: absolute;\n    display: flex;\n    flex-direction: row;\n    justify-content: flex-end;\n    text-align: right;\n    /* text-align-last: justify; */\n    left: -2.5cm;\n  }\n\n  .event {\n    position: relative;\n    margin: 4px 0;\n    display: flex;\n    align-items: flex-start;\n    width: max-content;\n}\n\n  .dot {\n    border-radius: 5px;\n  }\n  .event .content {\n    margin-left: 40px;\n    padding: 4px 10px;\n    background-color: white;\n    border-radius: 5px;\n    box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);\n    position: relative;\n    left: -2em;\n    /* left: calc(var(--offset) / 1 - 30px); */\n    z-index: 1;\n    width: 9.2cm;\n}\n  .event .content h3 {\n    font-size: inherit;\n    margin: 0;\n}\n\n    .event-company, .event-place {\n    color: #5a5a5a;\n    }\n\n  .content::before {\n    content: \"\";\n    position: absolute;\n    top: 4px;\n    left: 0;\n    width: 2px;\n    height: 1em;\n    \n    background: var(--color);\n    border-radius: 10px;\n    z-index: 0;\n    /* display: none; */\n  }\n}\n",
    "icons": "/* @rickcv-theme\n   name:     Icons\n   author:   RickCV\n   licence:  CC0-1.0\n   contract: 1\n   about:    Symbole tragen das Layout: jede Station bekommt ihren Punkt,\n             die Zeitleiste laeuft mittig.\n   about-en: Symbols carry the layout: every station gets its dot, the\n             timeline runs down the middle.\n*/\n\n[data-template] {\n\n\n  .timeline {\n    position: relative;\n    margin: 0 auto;\n    padding: 20px 0;\n    /* margin-left: 4em; */\n    width: 300px;\n    padding-top: 0;\n    padding-bottom: 0;\n    display: flex;\n    flex-wrap: wrap;\n    left: .3cm;\n}\n\n .event {\n    position: relative;\n    margin: 12px 0;\n    margin: auto 0;\n    display: flex;\n    align-items: flex-start;\n    width: 28em;\n  }\n  .date {\n    position: absolute;\n    width: 4em;\n    right: 2.5em;\n    display: flex;\n    flex-direction: row;\n    justify-content: flex-end;\n    text-align: right;\n    /* text-align-last: justify; */\n    left: inherit;\n  }\n  .dot {\n    width: 30px;\n    height: 30px;\n    min-width: 30px;\n    min-height: 30px;\n    border-radius: 12%;\n    display: flex;\n    align-items: center;\n    justify-content: center;\n    color: white;\n    font-size: 16px;\n    position: relative;\n    z-index: 1;\n    background: var(--color);\n    left: -2.9cm;\n    top: -2px;\n    /* left: calc(1* var(--offset)); */\n    /* visibility: hidden; */\n    z-index: 2;\n}\n\n.event .content {\n  margin-left: 0;\n  padding-top: 0;\n  background-color: var(--background-color);\n  border-radius: 5px;\n  box-shadow: none;\n  position: relative;\n  left: -3cm;\n  /* left: calc(var(--offset) / 1 - 30px); */\n  z-index: 1;\n  /* width: 20cm; */\n  /* max-width: 16cm; */\n  min-width: 10cm;\n  flex: 10;\n  padding-right: 0;\n}\n\n  .event .content h3 {\n    font-size: inherit;\n    margin: 0;\n }\n\n  .event-company, .event-place {\n    color: #5a5a5a;\n  }\n\n  .content::before {\n    content: \"\";\n    position: absolute;\n    top: 4px;\n    left: 0;\n    width: 2px;\n    height: 1em;\n    background: var(--accent-color);\n    border-radius: 10px;\n    z-index: 0;\n    visibility: hidden;\n}\n\n\n.line {\n  position: absolute;\n  width: 4px;\n  background: var(--color);\n  left: calc(13px + var(--offset) / 4);\n  top: 0;\n  border-radius: 20px;\n  z-index: 0;\n  height: 0;\n  /* display: none; */\n  transform: translateX(-2.9cm);\n}\n\n\n.timeline::before {\n  content: \"\";\n  position: absolute;\n  left: 13px;\n  top: 0;\n  bottom: 0;\n  width: 4px;\n  background-color: #ccc;\n  z-index: 0;\n  transform: translateX(-2.9cm);\n}\n\n}\n"
  };
})(typeof window !== "undefined" ? window : this);
